# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compaData.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1470, 966)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1471, 961))
        self.tabWidget.setObjectName("tabWidget")
        self.v3D = QtWidgets.QWidget()
        self.v3D.setObjectName("v3D")
        self.Frame1 = QtWidgets.QWidget(self.v3D)
        self.Frame1.setGeometry(QtCore.QRect(10, 100, 701, 721))
        self.Frame1.setObjectName("Frame1")
        self.Frame2 = QtWidgets.QWidget(self.v3D)
        self.Frame2.setGeometry(QtCore.QRect(750, 100, 701, 721))
        self.Frame2.setObjectName("Frame2")
        self.combbprincipal = QtWidgets.QComboBox(self.v3D)
        self.combbprincipal.setGeometry(QtCore.QRect(480, 40, 471, 28))
        self.combbprincipal.setStyleSheet("QCombobox {\n"
"    background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.combbprincipal.setObjectName("combbprincipal")
        self.combbprincipal.addItem("")
        self.combbprincipal.addItem("")
        self.tabWidget.addTab(self.v3D, "")
        self.Scatters = QtWidgets.QWidget()
        self.Scatters.setObjectName("Scatters")
        self.graph_scatter_cd = QtWidgets.QPushButton(self.Scatters)
        self.graph_scatter_cd.setGeometry(QtCore.QRect(370, 80, 131, 41))
        self.graph_scatter_cd.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.graph_scatter_cd.setObjectName("graph_scatter_cd")
        self.label_6 = QtWidgets.QLabel(self.Scatters)
        self.label_6.setGeometry(QtCore.QRect(750, 90, 221, 20))
        self.label_6.setObjectName("label_6")
        self.boxcd = QtWidgets.QComboBox(self.Scatters)
        self.boxcd.setGeometry(QtCore.QRect(1030, 30, 221, 28))
        self.boxcd.setObjectName("boxcd")
        self.boxcd.addItem("")
        self.boxcd.addItem("")
        self.Frame3 = QtWidgets.QWidget(self.Scatters)
        self.Frame3.setGeometry(QtCore.QRect(20, 180, 701, 721))
        self.Frame3.setObjectName("Frame3")
        self.label_12 = QtWidgets.QLabel(self.Scatters)
        self.label_12.setGeometry(QtCore.QRect(90, 30, 221, 20))
        self.label_12.setObjectName("label_12")
        self.Frame4 = QtWidgets.QWidget(self.Scatters)
        self.Frame4.setGeometry(QtCore.QRect(740, 180, 701, 721))
        self.Frame4.setObjectName("Frame4")
        self.direction_cd = QtWidgets.QCheckBox(self.Scatters)
        self.direction_cd.setGeometry(QtCore.QRect(1170, 90, 181, 26))
        self.direction_cd.setObjectName("direction_cd")
        self.scttlabel_cd = QtWidgets.QCheckBox(self.Scatters)
        self.scttlabel_cd.setGeometry(QtCore.QRect(1170, 130, 151, 26))
        self.scttlabel_cd.setObjectName("scttlabel_cd")
        self.colorbar_cd = QtWidgets.QCheckBox(self.Scatters)
        self.colorbar_cd.setGeometry(QtCore.QRect(1000, 90, 93, 26))
        self.colorbar_cd.setObjectName("colorbar_cd")
        self.secondax_cd = QtWidgets.QCheckBox(self.Scatters)
        self.secondax_cd.setGeometry(QtCore.QRect(1000, 130, 121, 26))
        self.secondax_cd.setObjectName("secondax_cd")
        self.Y_Value_cd = QtWidgets.QLineEdit(self.Scatters)
        self.Y_Value_cd.setGeometry(QtCore.QRect(150, 130, 113, 28))
        self.Y_Value_cd.setText("")
        self.Y_Value_cd.setObjectName("Y_Value_cd")
        self.label_14 = QtWidgets.QLabel(self.Scatters)
        self.label_14.setGeometry(QtCore.QRect(280, 130, 63, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.Scatters)
        self.label_15.setGeometry(QtCore.QRect(280, 80, 63, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.Scatters)
        self.label_16.setGeometry(QtCore.QRect(80, 80, 63, 20))
        self.label_16.setObjectName("label_16")
        self.X_value_cd = QtWidgets.QLineEdit(self.Scatters)
        self.X_value_cd.setGeometry(QtCore.QRect(150, 80, 113, 28))
        self.X_value_cd.setText("")
        self.X_value_cd.setObjectName("X_value_cd")
        self.label_17 = QtWidgets.QLabel(self.Scatters)
        self.label_17.setGeometry(QtCore.QRect(80, 130, 63, 20))
        self.label_17.setObjectName("label_17")
        self.tabWidget.addTab(self.Scatters, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.combbprincipal.setItemText(0, _translate("Form", "Volume rendering"))
        self.combbprincipal.setItemText(1, _translate("Form", "Isosurface"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.v3D), _translate("Form", "Comparison 3D visualisation "))
        self.graph_scatter_cd.setText(_translate("Form", "Graph"))
        self.label_6.setText(_translate("Form", "Graph configuration "))
        self.boxcd.setItemText(0, _translate("Form", "Circle"))
        self.boxcd.setItemText(1, _translate("Form", "Cross"))
        self.label_12.setText(_translate("Form", "Please write the desired values "))
        self.direction_cd.setText(_translate("Form", "Change axes direction"))
        self.scttlabel_cd.setText(_translate("Form", "Scatter label"))
        self.colorbar_cd.setText(_translate("Form", "Color bar"))
        self.secondax_cd.setText(_translate("Form", "Second Axis"))
        self.label_14.setText(_translate("Form", "mm"))
        self.label_15.setText(_translate("Form", "mm"))
        self.label_16.setText(_translate("Form", "X-value"))
        self.label_17.setText(_translate("Form", "Y-value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Scatters), _translate("Form", "Comparison scatters visualisation "))
