# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'compaData.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1450, 880)
        self.Title_d = QtWidgets.QLabel(Form)
        self.Title_d.setGeometry(QtCore.QRect(610, 20, 221, 31))
        self.Title_d.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 16pt \"Segoe UI\";")
        self.Title_d.setObjectName("Title_d")
        self.combbprincipal = QtWidgets.QComboBox(Form)
        self.combbprincipal.setGeometry(QtCore.QRect(490, 80, 471, 28))
        self.combbprincipal.setStyleSheet("QCombobox {\n"
"    background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.combbprincipal.setObjectName("combbprincipal")
        self.combbprincipal.addItem("")
        self.combbprincipal.addItem("")
        self.buttonGraph = QtWidgets.QPushButton(Form)
        self.buttonGraph.setGeometry(QtCore.QRect(660, 820, 141, 29))
        self.buttonGraph.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.buttonGraph.setObjectName("buttonGraph")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(350, 40, 821, 20))
        self.label.setObjectName("label")
        self.Frame2 = QtWidgets.QWidget(Form)
        self.Frame2.setGeometry(QtCore.QRect(730, 140, 701, 641))
        self.Frame2.setObjectName("Frame2")
        self.Frame2_2 = QtWidgets.QWidget(Form)
        self.Frame2_2.setGeometry(QtCore.QRect(10, 140, 701, 641))
        self.Frame2_2.setObjectName("Frame2_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title_d.setText(_translate("Form", "Data comparison "))
        self.combbprincipal.setItemText(0, _translate("Form", "3D Visualization"))
        self.combbprincipal.setItemText(1, _translate("Form", "Axes "))
        self.buttonGraph.setText(_translate("Form", "Graph "))
        self.label.setText(_translate("Form", "______________________________________________________________________________________________________________________________"))
