# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up_scatter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(325, 224)
        self.X_value_s = QtWidgets.QLineEdit(Form)
        self.X_value_s.setGeometry(QtCore.QRect(110, 70, 113, 28))
        self.X_value_s.setText("")
        self.X_value_s.setObjectName("X_value_s")
        self.Y_Value_s = QtWidgets.QLineEdit(Form)
        self.Y_Value_s.setGeometry(QtCore.QRect(110, 120, 113, 28))
        self.Y_Value_s.setText("")
        self.Y_Value_s.setObjectName("Y_Value_s")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 20, 221, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 63, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 63, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(230, 70, 63, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(230, 120, 63, 20))
        self.label_5.setObjectName("label_5")
        self.graph_scatter = QtWidgets.QPushButton(Form)
        self.graph_scatter.setGeometry(QtCore.QRect(110, 170, 111, 31))
        self.graph_scatter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.graph_scatter.setObjectName("graph_scatter")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Please write the desired values "))
        self.label_2.setText(_translate("Form", "X-value"))
        self.label_3.setText(_translate("Form", "Y-value"))
        self.label_4.setText(_translate("Form", "mm"))
        self.label_5.setText(_translate("Form", "mm"))
        self.graph_scatter.setText(_translate("Form", "Graph"))
