# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\principalwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1601, 913)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Widget.sizePolicy().hasHeightForWidth())
        Widget.setSizePolicy(sizePolicy)
        Widget.setStyleSheet("QWidget {\n"
"    background-color: rgb(222, 222, 222)\n"
"     \n"
"    border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.33 rgba(0, 0, 0, 255), stop:0.34 rgba(255, 30, 30, 255), stop:0.66 rgba(255, 0, 0, 255), stop:0.67 rgba(255, 255, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
"}")
        self.gridLayoutWidget = QtWidgets.QWidget(Widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(850, 80, 681, 691))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.viLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.viLayout.setContentsMargins(0, 0, 0, 0)
        self.viLayout.setObjectName("viLayout")
        self.comboBox = QtWidgets.QComboBox(Widget)
        self.comboBox.setGeometry(QtCore.QRect(980, 20, 459, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setCurrentText("")
        self.comboBox.setMaxVisibleItems(2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayoutWidget = QtWidgets.QWidget(Widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 491, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fileText = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.fileText.setObjectName("fileText")
        self.verticalLayout_2.addWidget(self.fileText)
        self.openFile = QtWidgets.QPushButton(Widget)
        self.openFile.setGeometry(QtCore.QRect(670, 20, 80, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFile.sizePolicy().hasHeightForWidth())
        self.openFile.setSizePolicy(sizePolicy)
        self.openFile.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.openFile.setAutoExclusive(False)
        self.openFile.setObjectName("openFile")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Widget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 240, 721, 591))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.visxy = QtWidgets.QWidget()
        self.visxy.setObjectName("visxy")
        self.tabWidget.addTab(self.visxy, "")
        self.viszy = QtWidgets.QWidget()
        self.viszy.setObjectName("viszy")
        self.tabWidget.addTab(self.viszy, "")
        self.visxz = QtWidgets.QWidget()
        self.visxz.setObjectName("visxz")
        self.tabWidget.addTab(self.visxz, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.scatter = QtWidgets.QPushButton(Widget)
        self.scatter.setGeometry(QtCore.QRect(940, 810, 201, 41))
        self.scatter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.scatter.setObjectName("scatter")
        self.textInfo = QtWidgets.QTextBrowser(Widget)
        self.textInfo.setGeometry(QtCore.QRect(20, 70, 741, 151))
        self.textInfo.setObjectName("textInfo")
        self.horizontalSlider = QtWidgets.QSlider(Widget)
        self.horizontalSlider.setGeometry(QtCore.QRect(450, 850, 160, 18))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(350, 870, 391, 20))
        self.label.setObjectName("label")
        self.comboBox_2 = QtWidgets.QComboBox(Widget)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 850, 221, 28))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.FWHM = QtWidgets.QPushButton(Widget)
        self.FWHM.setGeometry(QtCore.QRect(1270, 810, 201, 41))
        self.FWHM.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.FWHM.setObjectName("FWHM")

        self.retranslateUi(Widget)
        self.comboBox.setCurrentIndex(-1)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "3D File Visualizer & Modeling Tool (Medizin Technick)"))
        self.comboBox.setItemText(0, _translate("Widget", "Isosurface"))
        self.comboBox.setItemText(1, _translate("Widget", "Volume rendering"))
        self.fileText.setText(_translate("Widget", "Please select a file"))
        self.openFile.setText(_translate("Widget", "Open File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visxy), _translate("Widget", "Axis xy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viszy), _translate("Widget", "Axis yz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.visxz), _translate("Widget", "Axis xz"))
        self.scatter.setText(_translate("Widget", "Scatterer positions"))
        self.label.setText(_translate("Widget", "Position : "))
        self.comboBox_2.setItemText(0, _translate("Widget", "Milimeters"))
        self.comboBox_2.setItemText(1, _translate("Widget", "Wavelength "))
        self.FWHM.setText(_translate("Widget", "FWHM"))
