# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pop_up_scatter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1386, 828)
        self.X_value_s = QtWidgets.QLineEdit(Form)
        self.X_value_s.setGeometry(QtCore.QRect(1160, 150, 113, 28))
        self.X_value_s.setText("")
        self.X_value_s.setObjectName("X_value_s")
        self.Y_Value_s = QtWidgets.QLineEdit(Form)
        self.Y_Value_s.setGeometry(QtCore.QRect(1160, 200, 113, 28))
        self.Y_Value_s.setText("")
        self.Y_Value_s.setObjectName("Y_Value_s")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(1120, 100, 221, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1080, 150, 63, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1080, 200, 63, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1280, 150, 63, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1280, 200, 63, 20))
        self.label_5.setObjectName("label_5")
        self.graph_scatter = QtWidgets.QPushButton(Form)
        self.graph_scatter.setGeometry(QtCore.QRect(1160, 340, 111, 31))
        self.graph_scatter.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.graph_scatter.setObjectName("graph_scatter")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(20, 40, 1001, 761))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.boxxoro = QtWidgets.QComboBox(Form)
        self.boxxoro.setGeometry(QtCore.QRect(1150, 270, 141, 28))
        self.boxxoro.setObjectName("boxxoro")
        self.boxxoro.addItem("")
        self.boxxoro.addItem("")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(1090, 450, 221, 20))
        self.label_6.setObjectName("label_6")
        self.colorbar = QtWidgets.QCheckBox(Form)
        self.colorbar.setGeometry(QtCore.QRect(1120, 510, 93, 26))
        self.colorbar.setObjectName("colorbar")
        self.secondax = QtWidgets.QCheckBox(Form)
        self.secondax.setGeometry(QtCore.QRect(1120, 550, 121, 26))
        self.secondax.setObjectName("secondax")
        self.direction = QtWidgets.QCheckBox(Form)
        self.direction.setGeometry(QtCore.QRect(1120, 590, 151, 26))
        self.direction.setObjectName("direction")
        self.axlabel = QtWidgets.QCheckBox(Form)
        self.axlabel.setGeometry(QtCore.QRect(1120, 630, 151, 26))
        self.axlabel.setObjectName("axlabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Please write the desired values "))
        self.label_2.setText(_translate("Form", "X-value"))
        self.label_3.setText(_translate("Form", "Y-value"))
        self.label_4.setText(_translate("Form", "mm"))
        self.label_5.setText(_translate("Form", "mm"))
        self.graph_scatter.setText(_translate("Form", "Graph"))
        self.boxxoro.setItemText(0, _translate("Form", "Circle"))
        self.boxxoro.setItemText(1, _translate("Form", "Ex"))
        self.label_6.setText(_translate("Form", "Extra options - configuration"))
        self.colorbar.setText(_translate("Form", "Color bar"))
        self.secondax.setText(_translate("Form", "Second Ax"))
        self.direction.setText(_translate("Form", "Change direction"))
        self.axlabel.setText(_translate("Form", "Axes label"))
