# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scatterwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1584, 887)
        Dialog.setMinimumSize(QtCore.QSize(913, 0))
        self.combbprincipal = QtWidgets.QComboBox(Dialog)
        self.combbprincipal.setGeometry(QtCore.QRect(170, 120, 471, 28))
        self.combbprincipal.setStyleSheet("QCombobox {\n"
"    background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.combbprincipal.setObjectName("combbprincipal")
        self.combbprincipal.addItem("")
        self.combbprincipal.addItem("")
        self.InputIndex = QtWidgets.QLineEdit(Dialog)
        self.InputIndex.setGeometry(QtCore.QRect(290, 760, 113, 28))
        self.InputIndex.setText("")
        self.InputIndex.setObjectName("InputIndex")
        self.label_x = QtWidgets.QLabel(Dialog)
        self.label_x.setGeometry(QtCore.QRect(80, 760, 191, 20))
        self.label_x.setObjectName("label_x")
        self.FrameX = QtWidgets.QWidget(Dialog)
        self.FrameX.setGeometry(QtCore.QRect(60, 270, 481, 471))
        self.FrameX.setObjectName("FrameX")
        self.Title = QtWidgets.QLabel(Dialog)
        self.Title.setGeometry(QtCore.QRect(650, 50, 221, 31))
        self.Title.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 16pt \"Segoe UI\";")
        self.Title.setObjectName("Title")
        self.FrameY = QtWidgets.QWidget(Dialog)
        self.FrameY.setGeometry(QtCore.QRect(550, 270, 481, 471))
        self.FrameY.setObjectName("FrameY")
        self.FrameZ = QtWidgets.QWidget(Dialog)
        self.FrameZ.setGeometry(QtCore.QRect(1040, 270, 481, 471))
        self.FrameZ.setObjectName("FrameZ")
        self.combbsimu = QtWidgets.QComboBox(Dialog)
        self.combbsimu.setGeometry(QtCore.QRect(170, 170, 451, 28))
        self.combbsimu.setObjectName("combbsimu")
        self.buttonGraph = QtWidgets.QPushButton(Dialog)
        self.buttonGraph.setGeometry(QtCore.QRect(520, 820, 141, 29))
        self.buttonGraph.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.buttonGraph.setObjectName("buttonGraph")
        self.label_y = QtWidgets.QLabel(Dialog)
        self.label_y.setGeometry(QtCore.QRect(620, 760, 191, 20))
        self.label_y.setObjectName("label_y")
        self.InputIndey = QtWidgets.QLineEdit(Dialog)
        self.InputIndey.setGeometry(QtCore.QRect(830, 760, 113, 28))
        self.InputIndey.setText("")
        self.InputIndey.setObjectName("InputIndey")
        self.label_z = QtWidgets.QLabel(Dialog)
        self.label_z.setGeometry(QtCore.QRect(1120, 760, 191, 20))
        self.label_z.setObjectName("label_z")
        self.InputIndez = QtWidgets.QLineEdit(Dialog)
        self.InputIndez.setGeometry(QtCore.QRect(1330, 760, 113, 28))
        self.InputIndez.setText("")
        self.InputIndez.setObjectName("InputIndez")
        self.InputZoom = QtWidgets.QLineEdit(Dialog)
        self.InputZoom.setGeometry(QtCore.QRect(1030, 131, 51, 20))
        self.InputZoom.setText("")
        self.InputZoom.setObjectName("InputZoom")
        self.zoomvalue = QtWidgets.QLabel(Dialog)
        self.zoomvalue.setGeometry(QtCore.QRect(880, 130, 191, 20))
        self.zoomvalue.setObjectName("zoomvalue")
        self.buttonTable = QtWidgets.QPushButton(Dialog)
        self.buttonTable.setGeometry(QtCore.QRect(950, 820, 141, 29))
        self.buttonTable.setStyleSheet("QPushButton {\n"
"    background-color: rgb(0, 0, 77);\n"
"    color: white;\n"
"}")
        self.buttonTable.setObjectName("buttonTable")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(880, 170, 321, 26))
        self.checkBox.setObjectName("checkBox")
        self.checkunits = QtWidgets.QCheckBox(Dialog)
        self.checkunits.setGeometry(QtCore.QRect(880, 210, 321, 26))
        self.checkunits.setObjectName("checkunits")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(400, 80, 821, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(700, 150, 63, 161))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Scatter/Wire Position"))
        self.combbprincipal.setItemText(0, _translate("Dialog", "Simulation peaks "))
        self.combbprincipal.setItemText(1, _translate("Dialog", "Manual input "))
        self.label_x.setText(_translate("Dialog", "Input index or position on X  "))
        self.Title.setText(_translate("Dialog", "Scatterer positions"))
        self.buttonGraph.setText(_translate("Dialog", "Graph "))
        self.label_y.setText(_translate("Dialog", "Input index or position on Y  "))
        self.label_z.setText(_translate("Dialog", "Input index or position on Z  "))
        self.zoomvalue.setText(_translate("Dialog", "Horizontal zoom "))
        self.buttonTable.setText(_translate("Dialog", "Table Values"))
        self.checkBox.setText(_translate("Dialog", "Normalise figures "))
        self.checkunits.setText(_translate("Dialog", "Change units to Lambda "))
        self.label.setText(_translate("Dialog", "______________________________________________________________________________________________________________________________"))
